DECLARE 
  TYPE MANAGERS IS TABLE OF EMPLOYEES%ROWTYPE
  INDEX BY PLS_INTEGER;
  V_MANAGERS MANAGERS;
  V_ROW EMPLOYEES%ROWTYPE;
  TEMP PLS_INTEGER;
BEGIN

    FOR X IN 101..206
    LOOP
    
        SELECT P.* INTO V_ROW FROM EMPLOYEES E, EMPLOYEES P 
        WHERE E.MANAGER_ID=P.EMPLOYEE_ID AND E.EMPLOYEE_ID=X;
        V_MANAGERS(X-99):=V_ROW;
        
    END LOOP;
    
    FOR X IN 101..206
    LOOP
      DBMS_OUTPUT.PUT_LINE(X || '  - ' ||V_MANAGERS(X-99).FIRST_NAME);
    END LOOP;
END;

