DECLARE
  V_WHAT VARCHAR(30);
  V_RESULT VARCHAR(100);
  V_ID PLS_INTEGER;
BEGIN
  V_WHAT:= '&WHAT';
  V_ID:= '&ID';
  CASE V_WHAT
     WHEN 'FIRSTNAME' THEN 
        SELECT FIRST_NAME INTO V_RESULT  FROM EMPLOYEES WHERE EMPLOYEE_ID=V_ID;
     WHEN 'LASTNAME' THEN
        SELECT LAST_NAME INTO V_RESULT  FROM EMPLOYEES WHERE EMPLOYEE_ID=V_ID;
     WHEN 'HIREDATE' THEN
        SELECT HIRE_DATE INTO V_RESULT  FROM EMPLOYEES WHERE EMPLOYEE_ID=V_ID;
    ELSE
        V_RESULT:= 'NOTHING';
    END CASE;
    DBMS_OUTPUT.PUT_LINE('FETCHED ' || V_WHAT || ' RESULT IS ' || V_RESULT);
END;

