DECLARE
  CURSOR MYCURSOR(X NUMBER) IS (SELECT * FROM COUNTRIES WHERE REGION_ID= X);
  V_COUNTRY COUNTRIES%ROWTYPE;
BEGIN
    OPEN MYCURSOR(4);
    LOOP
      FETCH MYCURSOR INTO V_COUNTRY;
      EXIT WHEN MYCURSOR%NOTFOUND;
    
      DBMS_OUTPUT.PUT_LINE(V_COUNTRY.COUNTRY_NAME);
     
    END LOOP;
    CLOSE MYCURSOR;
END;
