DECLARE
  CURSOR MYCURSOR IS (SELECT * FROM COUNTRIES);
  V_COUNTRY COUNTRIES%ROWTYPE;
BEGIN
    OPEN MYCURSOR;
    LOOP
      FETCH MYCURSOR INTO V_COUNTRY;
      EXIT WHEN MYCURSOR%NOTFOUND;
      IF V_COUNTRY.REGION_ID=4 THEN
      DBMS_OUTPUT.PUT_LINE(V_COUNTRY.COUNTRY_NAME);
      END IF;
    END LOOP;
    CLOSE MYCURSOR;
END;
