DECLARE
  CURSOR MYCURSOR IS (SELECT * FROM MYDEPTS) FOR UPDATE OF HEADQUARTER;
  TYPE CITIES IS VARRAY(10) OF VARCHAR(20);
  V_CITIES CITIES;
  V_START PLS_INTEGER:=1;
  V_DEPT MYDEPTS%ROWTYPE;
BEGIN
    V_CITIES:=CITIES('CAIRO','DUBAI','COLUMBO','CHENNAI','MUMBAI','CHICAGO','TOKYO');
    OPEN MYCURSOR;
    LOOP
      FETCH MYCURSOR INTO V_DEPT;
      EXIT WHEN MYCURSOR%NOTFOUND;
      UPDATE MYDEPTS SET HEADQUARTER=V_CITIES(V_START) WHERE DEPARTMENT_ID =v_DEPT.DEPARTMENT_ID;
      V_START:= V_START + 1;
      
      IF V_START = 8 THEN
         V_START:=1;
      END IF;
      
    END LOOP;
    COMMIT;
    CLOSE MYCURSOR;
END;
