DECLARE
  V_ID PLS_INTEGER;
  V_NAME VARCHAR(30);
BEGIN 
  V_ID:=&ID;
  SELECT FIRST_NAME INTO V_NAME FROM EMPLOYEES WHERE DEPARMENT_ID=V_ID;
  DBMS_OUTPUT.PUT_LINE(V_NAME);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('ID IS NOT VALID');
   WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('SOME EXCEPTION'||SQLERR);

END;