DECLARE
  V_ID PLS_INTEGER;
  V_NAME VARCHAR(30);
  INVALID_ID_EXCEPTION EXCEPTION;
  PRAGMA EXCEPTION_INIT(INVALID_ID_EXCEPTION, -20101);
BEGIN 
  V_ID:=&ID;
  IF V_ID  NOT BETWEEN 100 AND 206 THEN
    RAISE_APPLICATION_ERROR(-20101, ' ID MUST BE BETWEEN 100 AND 206');
  END IF;
  SELECT FIRST_NAME INTO V_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID=V_ID;
  DBMS_OUTPUT.PUT_LINE(V_NAME);
EXCEPTION
   WHEN NO_DATA_FOUND THEN
     DBMS_OUTPUT.PUT_LINE('ID IS NOT VALID');
   WHEN INVALID_ID_EXCEPTION THEN
     DBMS_OUTPUT.PUT_LINE('WRONG ID'||SQLCODE||'  '||SQLERRM);
   WHEN OTHERS THEN
     DBMS_OUTPUT.PUT_LINE('SOME EXCEPTION '||SQLCODE||'  '||SQLERRM);

END;