DECLARE
  V_LINE VARCHAR(300);
  V_FILE UTL_FILE.FILE_TYPE;
BEGIN
   V_FILE := UTL_FILE.FOPEN('HR_DIRECTORY','COUNTRIES.txt','W');
   FOR X IN (SELECT * FROM COUNTRIES)
   LOOP
      UTL_FILE.PUT_LINE(V_FILE,X.COUNTRY_ID||', '||X.COUNTRY_NAME);
   END LOOP;

UTL_FILE.FCLOSE(V_FILE);
END;