DECLARE 
  V_RECORD EMPLOYEES%ROWTYPE;
BEGIN
     FOR X IN REVERSE 100..206
     LOOP
       SELECT * INTO V_RECORD FROM EMPLOYEES WHERE EMPLOYEE_ID=X;
       CONTINUE WHEN MOD(X,5)=0 OR  MOD(X,7)=0;
       DBMS_OUTPUT.PUT_LINE(V_RECORD.EMPLOYEE_ID||'  '||V_RECORD.FIRST_NAME || ' ' || V_RECORD.SALARY);
     END LOOP;
 
END;