DECLARE
   V_MAX PLS_INTEGER;
BEGIN
    SELECT MAX(SALARY) INTO V_MAX FROM EMPLOYEES;
    
    IF V_MAX>30000 THEN 
       DBMS_OUTPUT.PUT_LINE('30000+ $ IS A GREAT THING');
    ELSIF V_MAX>20000 THEN
       DBMS_OUTPUT.PUT_LINE(V_MAX || ' IS WHAT THIS COMPANY OFFERS MAX');
    ELSIF V_MAX>10000 THEN
       DBMS_OUTPUT.PUT_LINE('MAX SALARY NOT EVEN TOUCHING 20K');
    ELSE
       DBMS_OUTPUT.PUT_LINE('ONE OF THE LEAST PAID COMPANIES');
    END IF;
END;

SET SERVEROUTPUT ON;