DECLARE 
  V_RECORD EMPLOYEES%ROWTYPE;
  V_TIMES PLS_INTEGER;
  V_ID PLS_INTEGER;
  V_INIT PLS_INTEGER:=0;
BEGIN
   V_TIMES:= &HOWMANY;
   V_ID:=&ID;
   LOOP
    
     SELECT * INTO V_RECORD FROM EMPLOYEES WHERE EMPLOYEE_ID=V_ID;
     DBMS_OUTPUT.PUT_LINE(V_RECORD.EMPLOYEE_ID||'  '||V_RECORD.FIRST_NAME||'  '||V_RECORD.SALARY);
     V_INIT:=V_INIT+1;
     V_ID:=V_ID+1;
     EXIT WHEN V_INIT = V_TIMES;
   END LOOP;
END;