create or replace PACKAGE MATHEMATICS IS
   TYPE NUMBERS IS TABLE OF PLS_INTEGER;
   TYPE INDEXEDRESULTS IS TABLE OF NUMBERS INDEX BY PLS_INTEGER;
   PROCEDURE FACTORS(INPUTPARAM NUMBERS,OUTPUT OUT INDEXEDRESULTS);
   FUNCTION SQUARE(INPUTPARAM NUMBERS) RETURN NUMBERS;
   FUNCTION TOTAL(INPUTPARAM NUMBERS) RETURN PLS_INTEGER;
END MATHEMATICS;