DECLARE 
  MY_ARRAY MATHEMATICS.NUMBERS:=MATHEMATICS.NUMBERS(1,35,634,34,1);
BEGIN
  DBMS_OUTPUT.PUT_LINE(MATHEMATICS.TOTAL(MY_ARRAY));
END;


DECLARE 
   MY_ARRAY MATHEMATICS.NUMBERS:=MATHEMATICS.NUMBERS(12,5,13,18,25);
   MY_RESULT MATHEMATICS.NUMBERS;
BEGIN
     MY_RESULT:=MATHEMATICS.SQUARE(MY_ARRAY);
     FOR X IN 1..MY_RESULT.COUNT
     LOOP
       DBMS_OUTPUT.PUT_LINE(MY_ARRAY(X)||'  '||MY_RESULT(X));
     END LOOP;
END;

DECLARE
   MY_ARRAY MATHEMATICS.NUMBERS:=MATHEMATICS.NUMBERS(120,15,130,81,25);
   MYRESULT MATHEMATICS.INDEXEDRESULTS;
   TEMP MATHEMATICS.NUMBERS;
BEGIN
   MATHEMATICS.FACTORS(MY_ARRAY,MYRESULT);
   FOR X IN 1..MY_ARRAY.COUNT
     LOOP
         DBMS_OUTPUT.PUT_LINE('FACTORS OF ' || MY_ARRAY(X));
         TEMP:=MYRESULT(X);
         FOR X IN 1..TEMP.COUNT
           LOOP
           DBMS_OUTPUT.PUT_LINE(TEMP(X));
           END LOOP;
           DBMS_OUTPUT.PUT_LINE('--------------------------------------');
        END LOOP;
    
           
END;