CREATE OR REPLACE PROCEDURE FIRST_PROCEDURE(DEPTNO NUMBER)
IS
  CURSOR MYCUR(DNO NUMBER) IS (SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID=DNO);
  V_RECORD EMPLOYEES%ROWTYPE;
BEGIN
   FOR X IN MYCUR(DEPTNO)
   LOOP  
      DBMS_OUTPUT.PUT_LINE(X.FIRST_NAME || ' ' ||X.SALARY);
   END LOOP;
END;

--WAY1
EXEC FIRST_PROCEDURE(50);
--WAY 2
BEGIN
 FIRST_PROCEDURE(70);
END;