DECLARE 
   TYPE MY_REC IS RECORD(
    SNO THINGS.ID%TYPE,
    NAME THINGS.NAME%TYPE);  --USER DEFINED COMPOSITE TYPE [RECORD]
    
   V_RECORD MY_REC;
BEGIN
   SELECT * INTO V_RECORD FROM THINGS WHERE ID=1;
   DBMS_OUTPUT.PUT_LINE(V_RECORD.SNO||' '||V_RECORD.NAME);
END;
