CREATE TABLE STERLING_ACCOUNT(
ACNO NUMBER(6)  PRIMARY KEY,
NAME VARCHAR2(30) NOT NULL,
BALANCE NUMBER(12,2) NOT NULL
);
INSERT INTO STERLING_ACCOUNT VALUES(1,'JAYA',10000);
COMMIT;
CREATE TABLE STERLING_TRANSACTION(
TCNO NUMBER(6) PRIMARY KEY,
AMOUNT NUMBER(10,2) NOT NULL,
ACNO NUMBER(6) REFERENCES STERLING_ACCOUNT(ACNO),
TYPE VARCHAR2(30) CHECK(TYPE IN('DEPOSIT','WITHDRAW'))
)

CREATE OR REPLACE FUNCTION BALANCE(ACNO NUMBER) RETURN NUMBER
IS
  BAL NUMBER;
BEGIN
    SELECT BALANCE INTO BAL FROM STERLING_ACCOUNT WHERE ACNO=ACNO;
    RETURN BAL;
END;

SELECT BALANCE(1) FROM DUAL;

CREATE OR REPLACE TRIGGER TRANSATION_TRIGGER 
BEFORE INSERT ON  STERLING_TRANSACTION 
FOR EACH ROW
BEGIN
    IF :NEW.TYPE ='DEPOSIT' THEN
       UPDATE STERLING_ACCOUNT SET BALANCE=BALANCE+:NEW.AMOUNT WHERE ACNO=:NEW.ACNO;
    
    ELSE
     IF :NEW.TYPE = 'WITHDRAW' AND :NEW.AMOUNT<=BALANCE(:NEW.ACNO) THEN
       UPDATE STERLING_ACCOUNT SET BALANCE=BALANCE-:NEW.AMOUNT WHERE ACNO=:NEW.ACNO;
     ELSIF :NEW.TYPE='WITHDRAW' THEN
        RAISE_APPLICATION_ERROR(-20205,'BALANCE IS NOT SUFFICIENT');
     END IF;
     END IF;
   
END;

INSERT INTO STERLING_TRANSACTION VALUES(3,5000,1,'DEPOSIT');

INSERT INTO STERLING_TRANSACTION VALUES(3,15000,1,'WITHDRAW');
SELECT * FROM STERLING_TRANSACTION;
SELECT * FROM STERLING_ACCOUNT;

COMMIT;