DECLARE 
  TYPE PEOPLE IS VARRAY(110) OF VARCHAR(30);
  V_PEOPLE PEOPLE;
  V_SIZE PLS_INTEGER;
BEGIN
   V_PEOPLE:=PEOPLE();
  
   FOR I IN 100..206
   LOOP
     V_PEOPLE.EXTEND;
     SELECT FIRST_NAME INTO V_PEOPLE(I-99) FROM EMPLOYEES WHERE EMPLOYEE_ID=I;
   END LOOP;
   
   FOR I IN V_PEOPLE.FIRST..V_PEOPLE.LAST
   LOOP
     DBMS_OUTPUT.PUT_LINE(V_PEOPLE(I));
   END LOOP;
END;