DECLARE 
  TYPE PEOPLE IS VARRAY(10) OF VARCHAR(30);
  V_PEOPLE PEOPLE;
  V_SIZE PLS_INTEGER;
BEGIN
   V_PEOPLE:=PEOPLE('RAJ','JAY','HARRY','TUCKER','RICKY');
   V_PEOPLE(1):='JOHNY';
   V_SIZE:=V_PEOPLE.COUNT;
   FOR I IN 1..V_SIZE
   LOOP
     DBMS_OUTPUT.PUT_LINE(V_PEOPLE(I));
   END LOOP;
   V_PEOPLE(3):='JERRY';
END;