DECLARE
  V_CONTINUE BOOLEAN:= TRUE;
  V_RECORD EMPLOYEES%ROWTYPE;
  V_START PLS_INTEGER:=100;
BEGIN
       WHILE V_CONTINUE
       LOOP
          SELECT * INTO V_RECORD FROM EMPLOYEES WHERE EMPLOYEE_ID=V_START;
          IF TRIM(TO_CHAR(V_RECORD.HIRE_DATE,'DAY')) IN ('FRIDAY','THURSDAY') THEN
             V_CONTINUE:=FALSE;
          END IF;
          DBMS_OUTPUT.PUT_lINE(V_RECORD.FIRST_NAME || ' RECRUITED ON ' || TO_CHAR(V_RECORD.HIRE_DATE,'DAY'));
          V_START:=V_START+1;
       END LOOP;
END;
